### ISSUE TITLE
The NPM package doesn't link to the Github repo

### ISSUE THREAD

**Issue by JDiPierro** [martyndavies/legit#10]
When evaluating an NPM package I like to take a quick peek at the source code. The NPM page for this package doesn't link to this repo, so I had to search through Github to find it.

**Comment by Aarbel** [comment]
true 

![image](https://user-images.githubusercontent.com/25119847/63613330-cfbb1000-c5e0-11e9-8c61-21a21620366c.png)

**Comment by martyndavies** [comment]
Yeah, I had mispelled 'repository'. Thanks for flagging, this has now been fixed!
