### ISSUE TITLE
Fake emails like dskjdsbdskjbdskjbdskhbdsqjshvfsqdjv@gmail.com pass legit test

### ISSUE THREAD

**Issue by Aarbel** [martyndavies/legit#11]
Seems you only verify domain, but not subdomain of email. 

Is there a reason or a technical limitation ?

**Comment by JDiPierro** [comment]
`dskjdsbdskjbdskjbdskhbdsqjshvfsqdjv@gmail.com` has no subdomain and `gmail.com` has a valid MX record? That's what this library checks for.

AFAIK there's no way to verify the username on the address is valid without attempting a send.

**Comment by Aarbel** [comment]
Do you know a library to simulate a send and know if the username exists ?

Thanks ;)

**Comment by martyndavies** [comment]
@Aarbel Thanks for the question, @JDiPierro is correct though, you can only check domain level with this lib because to check the existence of a username on a domain would require a send and I don't know of any way to simulate that without actually doing it.
