### ISSUE TITLE
Gives Error: queryMx EREFUSED gmail.com on server

### ISSUE THREAD

**Issue by DanaIliescu** [martyndavies/legit#12]
On localhost everything works great, but on a test server I get this:
```
Error validating email:  Error: Error: queryMx EREFUSED gmail.com
    at QueryReqWrap.dns.resolveMx [as callback] (/srv/node_modules/legit/src/index.js:13:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:213:10)
```

My usage:
```
async function getInvalidEmails(emails) {
	let invalidEmails = [];
	const promises = emails.map(async (email) => {
		await legit(email)
			.then((result) => {
				if (!result.isValid) invalidEmails.push(email);
			})
			.catch((err) => {
				console.log('Error validating email: ', err);
				invalidEmails.push(email);
			});
	});
  
	await Promise.all(promises);
	return invalidEmails;
}
```

Any reasons why this might happen?

**Comment by DanaIliescu** [comment]
@martyndavies ^

**Comment by ais-one** [comment]
does your test server have access to gmail.com domain? does it know how to result gmail.com to an IP? any firewall blockage? outbound rules? etc...

**Comment by martyndavies** [comment]
@DanaIliescu Firstly, sorry for taking ages to get back to you on this. The `EREFUSED` error will  return when the domain cannot be reached so as @ais-one said, likely that the server cannot reach the gmail.com domain in this instance.
