### ISSUE TITLE
MX resolving is inaccurate

### ISSUE THREAD

**Issue by andrejsm** [martyndavies/legit#2]
Unfortunately this module can't resolve all legit domains. For example orangelv.com is considered unresolved despite the fact that it has MX records.
The error says:
`{ [Error: queryMx ENODATA] code: 'ENODATA', errno: 'ENODATA', syscall: 'queryMx' }`

**Comment by tofutim** [comment]
That is a bit scary

**Comment by tofutim** [comment]
I just checked orangelv and it is legit for me:

This is a real email that can accept emails!
[{"exchange":"aspmx2.googlemail.com","priority":40},{"exchange":"alt2.aspmx.l.google.com","priority":30},{"exchange":"alt1.aspmx.l.google.com","priority":20},{"exchange":"aspmx3.googlemail.com","priority":50},{"exchange":"aspmx.l.google.com","priority":10}]

mx:orangelv.com   Find Problems    mx  
Pref	Hostname	IP Address	TTL	
10	aspmx.l.google.com	74.125.30.27	5 min	Blacklist Check      SMTP Test
10	aspmx.l.google.com	2607:f8b0:4003:c02::1b	5 min	Blacklist Check
20	alt1.aspmx.l.google.com	64.233.185.27	5 min	Blacklist Check      SMTP Test
20	alt1.aspmx.l.google.com	2607:f8b0:4002:c09::1b	5 min	Blacklist Check
30	alt2.aspmx.l.google.com	173.194.205.26	5 min	Blacklist Check      SMTP Test
30	alt2.aspmx.l.google.com	2607:f8b0:400d:c02::1a	5 min	Blacklist Check
40	aspmx2.googlemail.com	64.233.185.26	5 min	Blacklist Check      SMTP Test
40	aspmx2.googlemail.com	2607:f8b0:4002:c09::1b	5 min	Blacklist Check
50	aspmx3.googlemail.com	173.194.205.26	5 min	Blacklist Check      SMTP Test
50	aspmx3.googlemail.com	2607:f8b0:400d:c02::1b	5 min	Blacklist Check
