### ISSUE TITLE
Script shows email as valid even if it fails when I manually send an email to the address

### ISSUE THREAD

**Issue by karlclement** [martyndavies/legit#3]
I tried sending an email directly to 1qaz2wsx3edc4rfv5tgb@twitter.com and I received a failure to send. I then passed the email through the validation using nodejs implementation and it passed validation

```
test: function (req, res) {
    var checkEmail = require('legit');
    checkEmail('1qaz2wsx3edc4rfv5tgb@twitter.com', function(validation, addresses, err) {
      if (validation) {
          console.log('This is a real email that can accept emails!');
          console.log(JSON.stringify(addresses));
      } else {
          console.log('This domain cannot accept emails, you might want to remove it.');
      }
    });
  },
```

**Comment by karlclement** [comment]
@martyndavies ^

**Comment by regaw-leinad** [comment]
In the documentation, it states the following:
```If an email addresses domain is legit then the validation will be true```

This only validates the domain of the email (the part AFTER the @)

**Comment by JyotirmoyGoswami** [comment]
what about the part BEFORE @

**Comment by tofutim** [comment]
You can use another library, for example, email-validator

**Comment by JyotirmoyGoswami** [comment]
@karlclement  email-validator only validates if the email id is correct format . That is not the issue here.
Its about whether  the email is present in the email server or not....if i am not wrong..

**Comment by jerome-diver** [comment]
i see email-deep-validator npm package do the job to search for domain an mx user box exists...
